@Host = http://localhost:5058

GET {{Host}}/enqueue_static
Accept: application/json

###

GET {{Host}}/enqueue_class_instance
Accept: application/json


###

GET {{Host}}/enqueue_class_instance_bulk
Accept: application/json
